### ISSUE TITLE
Greetings workflow is not working

### ISSUE THREAD

**Issue by eoinhalpin99** [tom-halpin/chatting-with-ChatGPT#13]
I submitted a PR to this repository and the greetings GitHub workflow didn't trigger.

**Comment by tom-halpin** [comment]
Thank you @eoinhalpin99, for reporting. I will take a look, feel free to submit a PR if you have time to fix.

**Comment by tom-halpin** [comment]
Closing in anticipation of https://github.com/tom-halpin/chatting-with-ChatGPT/pull/15 resolving. Thx @eoinhalpin99
